name: Baseline Guardian Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install

      - name: Run Baseline Guardian Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node bin/scan.js -r ${{ github.repository }} -o report.json -m report.md

      - name: Upload scan reports
        uses: actions/upload-artifact@v4
        with:
          name: baseline-guardian-reports
          path: |
            report.json
            report.md


